# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sls-web-socket
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  profiel: serverless
  runtime: python3.6
  websocketApiName: serverless-chat-api
  websocketApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:*"
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  connectionManager:
    handler: handler.connection_manager
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultMessage:
    handler: handler.default_message
    events:
      - websocket:
          route: $default
  getRecentMessages:
    handler: handler.get_recent_messages
    events:
      - websocket:
          route: getRecentMessages
  sendMessages:
    handler: handler.send_message
    events:
      - websocket:
          route: sendMessage
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get

resources:
  Resources:
    slsChatConnect:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-chat_Connections
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: ConnectionID
            AttributeType: S
        KeySchema:
          - 
            AttributeName: ConnectionID
            KeyType: HASH
    slsChatMessages:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-chat_Messages
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: Room
            AttributeType: S
          -
            AttributeName: Index
            AttributeType: N
        KeySchema:
          - 
            AttributeName: Room
            KeyType: HASH
          - 
            AttributeName: Index
            KeyType: RANGE

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []